---
abstract: unknown
author:
  - 'Albert Cornelissen <acorn@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Date-FriendlyDelta
no_index:
  directory:
    - t
    - inc
requires:
  Date::Parse: 2.3
  DateTime: 1.03
  perl: 5.010001
resources:
  bugtracker: https://github.com/acornelissen/template-plugin-date-friendlydelta/issues
  homepage: https://metacpan.org/module/Template::Plugin::Date::FriendlyDelta
  license: http://dev.perl.org/licenses/
  repository: https://github.com/acornelissen/template-plugin-date-friendlydelta
version: 0.01
